version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      VuOR67GzF94HPl80vXGocyxds+GIp98gKHXiq4s/MCioPEUSTJ9LVIMpM3pel3i/hwgHNKUsK59fJ5x2p3qNsQ0otUwYHXbjg35bxhiAcrEpuxDDuXTNhJZVp1AcVvc4uurZpVZ9OZ0GV6BomoBh23cFLfNjQZfEcDHM20/Mn+IAusGpLUcYP31+pD0qD4WnOFBCKncvPjfz37wBppiDH6hWKHhC+5yCWbu8BWO/NXAKhutwRMTPENkniidjPebLC7CR5/5F622WCJh1Vde0Mb+BO95dz7eEAtdsuhu8nY3hewXr6Wpe6Q0YKgN0ScCL2yEk6EF2uBfiTzHlUlcn55Tt9E36UDEpY86pPS+seZRzlsViNfI+9McvPIrRTHhnRxdMKamO+LQ5HjRTyQmtvE8UQ60nAgyByHvLrwW9PLvGyMvpugrjQSrdD0Al4MIRS6Q5pHqFP20Btmit33StYTfknNGd/yFOTR9Ti4WhLGuJI5DDK/Xzhx4+kapDkfzj3vdUd32DXDwrorv4X4SMMZmmedidk0udTIMFcguQGnJ41AYQxtWLxPrAQ7/jr9EyaYVBm6xRzWNTekOxPVuPqsxq7BPtujuO4i9FFDNvzjUIKDonFMrCfu2Gk/SyPAsS+zCLM4GaEMlSJlL+RO7fOPZ+mLGHnUwE4OrjPADbUUc=
