version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      suc6k/U8/L0a2QNQKAGkdxmFgJaI9+Mm14zAodX9JhKlkvVsD0Z2aloFPPrJ/7rNGiOEjeXzLtMomwMU8R0uq1PywBD+NsN6CrtWYkHgW5L0SPfBXucOkyzKsv8iEzTtxNqEkYNFPN5BAfvcatEljqw33cwlfE+N2VldnOK6/iAO1AtECJXUkMdqU6XKtzQZ4xDZwonnZ8CWj1xreAH/4Ik7Jlx3Cg0YBx33dJl2KHoj+3v2CHLuEwMlq1pbqPEII7fOSBGf6Wagf3TyEBdVtdK/YKHDNUhghJWdjZVUowokRUYhq2kbhjMs2dHyD4ITaIJiTFycXxDznYVQWdAfUQwxvDS1SmBI5dGTxrr8I7HOraZ/32LGiLv1wzH5d3Qd/IArtTKrSU2opTbWgSmUy6O1BFdykPksAFbMY1HuLXrrBgkdQaGxyMhYkKnTyZQUhbYMPVp1QmkFp17qQR2cOEE+K6qxNxvbHBUNxbt8QpLObOyxU9n8ADaceDr4igLdNlcNyf5ofZvd49d/CKxo6UE0Gt0xzLM+7ry87MMpqbVUyP30e2W8TrBqN6LDTJMM22unkleZjU+DatWDhCkjRRkPofP08ltLDACSs+XCKbN9oxDza5dwln4D9wmDbDjPr9RI2CG5Hnkqvo6/gsFd8o9NdvhruQFHJsSu0jWQuvM=
