version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      nRw+Rj8drKMOMT+2USQz+bW/86wHvIoZS2kPJRsgKYFetWtmbqA2rbZzB3qjbieFjh0+2qQUXlWznRQqCnBa3fbndSdl/Vfh+RRSYNeFAfF5NP/kqqDuVjubGQKmp2f9dbUh8wrMtx+xCj9d7gBdQDcBHqG/XgdoW+UzbIHhm94EoKe6vSXp50Y58Og3juvA+RIHXfisAQ8kc+R4IC/gABpngch/Ip89SvXjhs5lKEr0ZfC9aQY99buPcpZnuqv7n/I2D2zm1UITiQNcqMpNQDT4de/6CUwaXo9yEUHyQctBRKbdTWZYiXjrRjI06CuAcWv0/ICPHcA9xBPXrNSbjtJEYcMBBqbIO7dzcLw3j/I2K4OmYluR91PYvRYnGlEG0k9yUcNmS6YSC6h+PSUcKjjujtQJM5sGtero4tacHkHpmqyERmndn/uA7v9QHRA7WxYxtTYmX3UtDtzEjY1RKst2X7HTH6uqhxcIltACLS3rR3zcdSTzPnrqYd9B0TqfDsJpj1bjH4gsHLBnmTkdJF63uvGExjT5yIOCVzR6JGqFkrEjeOSmLM0AlKHSUb9xu3p+pVa02HMe2t76upke0TmqfXf8EUs4bViGLr/0eSc17Bi82Q4DclfcM1nTifdpKnuZY+2unRu3gzkpyGWcH7zF3F1LKI+1+QkwL+SBHMg=
