version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      VdRNEmDSua3swyvc3Y+rjChIJ0vcGrmD0C+J/LX6js6k80N3U5aOMArArFbMH+dxkYUQCClIi1oubNEtK8bQ/49C5Lboo3hYbFzwC+veOcoNmam6QwOihRj+aXJIX61LaZiNS4RC3iAbhOhvtWp3AmyIMHuOuXLaA5abFz8NLBjhM1lh/tsR4qaEO3s5pVVAzrihchLFDKU7SLzPukWQLPkjWXZiNld2BZ95Z8+32RintnYl4r8MWGfIcP0RvL1UC15mQxoZJ2IFDma57+gBuXNuAQXGI/2Kp1eqUkaguqFzhEb0qlY0/lcaqDwedAJA5qkbL65WdG3WxRHX2mi+nD6R87J/T5TvSfzSs65Hl/DxFlMSaw3/ariXn18Qqa68IFBflE5wMjdHvOCnS5FAu26jeoTxpvT2EeGdYsZVgEo+6GguiOlA2Z2/dqbCtYGH/350gHRPqwC50Bz9UGW3D6cNFsgaRbLRQW3u5554iSnAJLNr/cM2JXhFodLSgZD0sFqnXDbC8A/SkXVhOMHYr8bDHa5isIoWAXon84iMnCUlGofKi0F4CaM/opHPH63Q9RyhPgrc5gYqAF9CUVJO2kpkCK5ZDVs3xIMQHyWTtBadupPTEJL8k2ff/J+F2wluoLbY3Y+xPXRvR++OGokeWLteW5cVdROUdfgkdweAsvM=
